FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 755 /work/application
EXPOSE 8080
USER 1001
ENTRYPOINT ["/work/application", "-Xmx128m", "-Xms64m"]
