spring.application.name=autoscaling-engine

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always


# ======================
# Metrics (Nginx)
# ======================
autoscaler.metrics.nginx.status-url=http://nginx/nginx_status

# ======================
# Cooldown
# ======================
autoscaler.cooldown.duration-seconds=30

# ======================
# Scaling policy
# ======================
autoscaler.scaling.scale-up-rps-threshold=50
autoscaler.scaling.scale-down-rps-threshold=15
autoscaler.scaling.min-instances=1
autoscaler.scaling.max-instances=10

# ======================
# Docker
# ======================
autoscaler.docker.service-name=upscaler_backend
autoscaler.docker.min-replicas=1
autoscaler.docker.max-replicas=10