resolver 127.0.0.11 valid=1s ipv6=off;

upstream backend_pool {
    zone backend_pool 64k;
    server backend:8080 resolve;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend_pool;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /nginx_status {
        stub_status;
        access_log off;
        allow all;
    }
}