quarkus.application.name=backend

# HTTP
quarkus.http.io-threads=2
quarkus.http.worker-threads=8
quarkus.http.accept-backlog=128

# Metrics
quarkus.micrometer.export.prometheus.enabled=true

# Health
quarkus.smallrye-health.ui.enable=false

# Native memory contract
quarkus.native.initial-heap-size=64m
quarkus.native.max-heap-size=128m
quarkus.native.thread-stack-size=512k
