spring.application.name=Backend

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=backend-service

# SERVER
server.tomcat.threads.max=400
server.tomcat.threads.min-spare=50

server.tomcat.accept-count=100
server.tomcat.max-connections=10000